version: '3.9'

services:
    lande-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: lande-app
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=${APP_ENV:-local}
            - APP_DEBUG=${APP_DEBUG}
            - APP_KEY=${APP_KEY}
        depends_on:
            mariadb:
                condition: service_healthy
        networks:
            - app-network
        expose:
            - "9000"

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "${APP_PORT}:80"
        volumes:
            - .:/var/www/html
            - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            lande-app:
                condition: service_started
        networks:
            - app-network

    mariadb:
        image: mariadb:10
        container_name: mariadb
        env_file:
            - .env
        environment:
            MARIADB_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
            MARIADB_HOST: '${DB_HOST}'
            MARIADB_DATABASE: '${DB_DATABASE}'
            MARIADB_USER: '${DB_USERNAME}'
            MARIADB_PASSWORD: '${DB_PASSWORD}'
        ports:
            - '${DB_PORT:-3306}:3306'
        volumes:
            - mariadb_data:/var/lib/mysql
        networks:
            - app-network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            retries: 3
            timeout: 5s

networks:
    app-network:
        driver: bridge

volumes:
    mariadb_data:
